name: "CI"
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [macos-latest, ubuntu-latest]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v12
