name: "Publish"
on:
  # Run only when pushing to master branch
  push:
    #branches:
    #  - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v12
    - name: Build
      run: nix-build -j 4
    - uses: actions/cache@v2
      with:
        path: |
          messages.json
    - name: Generate site 🔧
      run: |
        ./result/bin/zulip-archive generate
    - name: Deploy to GitHub Pages 🚀
      uses: JamesIves/github-pages-deploy-action@3.5.6
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: site
